name: flutter_modul_2_codelab
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  dio: ^5.5.0+1
  webview_flutter: ^4.8.0
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

